PROJECT_NAME: eCommercedemo
HOST_NAME: rehive-build-server
NAMESPACE: echarge-demo-staging
IMAGE: gcr.io/rehive-services/echarge-demo-staging
VIRTUAL_HOST: echarge.s.demos.rehive.io
CLUSTER: staging
CLUSTER_PROJECT: rehive-services
