# Default values for rehive-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 2
image:
  repository: gcr.io/rehive-services/bitcoin-hooks-service
  tag: 0.0.1
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 8000
ingress:
  enabled: true
  hosts:
    - bitcoin-hooks.services.rehive.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - bitcoin-hooks.services.rehive.io
      secretName: bitcoin-hooks-service-tls
  hosts:
    - bitcoin-hooks.services.rehive.io
database:
  volumeName: bitcoin-hooks-service-database-volume
  volumeSize: 100Gi
  gcePersistentDiskName: bitcoin-hooks-service-database
workersEnabled: true
workers:
  - name: scheduler-poll-blockchain
    internalPort: 8000
    replicaCount: 1
    command: 'python ./schedulers/poll_blockchain.py'
  - name: sheduler-detect-new-transactions
    internalPort: 8000
    replicaCount: 1
    command: 'python ./schedulers/detect_new_transactions.py'
  - name: scheduler-new-transaction-notifications
    internalPort: 8000
    replicaCount: 1
    command: 'python ./schedulers/new_transaction_notifications.py'
  - name: scheduler-confirmation-notifications
    internalPort: 8000
    replicaCount: 1
    command: 'python ./schedulers/confirmation_notifications.py'
