# Default values for rehive-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 2
image:
  repository: gcr.io/rehive-services/echarge-demo-staging
  tag: 0.0.3
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 8000
ingress:
  enabled: true
  hosts:
    - echarge.s.demos.rehive.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - echarge.s.demos.rehive.io
      secretName: echarge-demo-tls
  hosts:
    - echarge.s.demos.rehive.io
postgresEnabled: false
workersEnabled: false

