apiVersion: v1
kind: Namespace
metadata:
  name: echarge-demo-staging
---
apiVersion: v1
kind: Service
metadata:
  name: echarge-demo
  namespace: echarge-demo-staging
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: echarge-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echarge-demo
  namespace: echarge-demo-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echarge-demo
    spec:
      containers:
      - image: gcr.io/rehive-services/echarge-demo-staging:0.0.3
        imagePullPolicy: Always
        name: echarge-demo
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echarge-demo
  namespace: echarge-demo-staging
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - echarge.s.demos.rehive.io
    secretName: echarge-demo-tls
  rules:
  - host: echarge.s.demos.rehive.io
    http:
      paths:
      - path: /
        backend:
          serviceName: echarge-demo
          servicePort: 80
