kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.database.volumeName }}
  labels:
    release: {{ template "fullname" . }}
spec:
  capacity:
    storage: {{ .Values.database.volumeSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    fsType: "ext4"
    pdName: {{ .Values.database.gcePersistentDiskName }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      release: {{ template "fullname" . }}
---
apiVersion: v1
kind: Pod
metadata:
  name: database-postgres
  labels:
    name: database
    node: postgres
spec:
  containers:
    -
      name: postgres
      image: postgres
      ports:
        -
          containerPort: 5432
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data-volume
  volumes:
    - name: pg-data-volume
      persistentVolumeClaim:
        claimName: data-claim-1
---
apiVersion: v1
kind: Service
metadata:
  name: database-postgres-service
  labels:
    name: database
    node: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  externalIPs:
    - 192.168.99.100
  selector:
    name: database
    node: postgres
