apiVersion: v1
kind: Namespace
metadata:
  name: rehive-dashboard-staging
---
apiVersion: v1
kind: Service
metadata:
  name: rehive-dashboard
  namespace: rehive-dashboard-staging
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: rehive-dashboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rehive-dashboard
  namespace: rehive-dashboard-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rehive-dashboard
    spec:
      containers:
      - image: rehive/rehive-dashboard:0.8.0
        imagePullPolicy: Always
        name: rehive-dashboard
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rehive-dashboard
  namespace: rehive-dashboard-staging
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - staging.dashboard.rehive.com
    - www.staging.dashboard.rehive.com
    secretName: rehive-dashboard-tls
  rules:
  - host: staging.dashboard.rehive.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rehive-dashboard
          servicePort: 80
  - host: www.staging.dashboard.rehive.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rehive-dashboard
          servicePort: 80
